# Project Parameters

# Model Parameters
input_size: 3
hidden_size: 30
num_window_components: 10
num_mixture_components: 20
batch_size: 1
savedModelDir: './trained_models/'
testModelPath: './trained_models/'

# Dataset Parameters
DatasetDir: './data/'
num_workers: 1

# Training Parameters
trainModel: True
useGPU: False
resumeTraining: False
num_epochs: 10
num_processes: 1
max_norm: 400
# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-4
momentum: 0.9
nesterov: True
update_frequency: 2
# Learning Rate Scheduler Parameters
T_max: 10
T_mult: 2
eta_min: 1.0e-4
