# Project Parameters

# Model Parameters
image_size: [484, 512]
num_channels: 1
hidden_size: 5
num_layers: 2
output_size: 2
window_size: [1, 1]
batch_size: 2
savedModelDir: './trained_models/'
testModelPath: './trained_models/'

# Dataset Parameters
TrainingDataset: './data/Training'
TestingDataset: './data/Testing'
num_workers: 1

# Training Parameters
trainModel: True
useGPU: False
resumeTraining: False
num_epochs: 10
num_processes: 1
max_norm: 400
# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-4
momentum: 0.9
nesterov: True
update_frequency: 2
# Learning Rate Scheduler Parameters
T_max: 10
T_mult: 2
eta_min: 1.0e-4
