# Project Parameters

# Model Parameters
input_size: 3
hidden_size: 100
num_window_components: 10
num_mixture_components: 20
batch_size: 32
savedModelDir: './trained_models/'
testModelPath: './trained_models/Trained_Model_268_20.05.2018_18.07'

# Dataset Parameters
DatasetDir: './data/'
num_workers: 0
min_num_points: 300

# Testing Parameters
probability_bias: 0.5
eos_threshold: 0.3

# Training Parameters
trainModel: True
useGPU: False
resumeTraining: True
num_epochs: 50
max_norm: 100
# Optimizer Parameters
optimizer: 'Adam'
learning_rate: 1.0e-3
momentum: 0.9
nesterov: True
update_frequency: 2
